# src/main/resources/application.yml

spring:
  application:
    name: spring-study # 애플리케이션 이름 설정

  datasource:
    url: jdbc:mysql://localhost:3306/gdg_post?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jeffrey31505*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # (1)
    show-sql: true # (2) //update 될떄마다 쿼리를 작성
    properties:
      hibernate:
        format_sql: true # (3)

server:
  port: 8080 # 애플리케이션 서버 포트 설정

